### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by Flaburgan** [jaywink/the-federation.info#43]
The site needs a cool design and to separate content on multiple pages. I'm working on it, though I will probably not do the integration inside the code. You can see the current work at https://dev.the-federation.info. It should also solve https://github.com/jaywink/diaspora-hub/issues/14.

Before this can be pushed to master, we need to at least:
- [x] Change the node page URL #83
- [x] Finish the network page by temporary commenting the "up-to-date versions" section (see #57)
- [x] Fix CURDATE usage #60 
- [x] Do not display nodes chart on the node page #80 
- [x] Check the whole design is responsive, fix CSS glitch
- [x] Add nodes chart back to index page (disappeared with #85 )
- [x] Rename "Global stats (/global-stats)" to "Node list (/nodes)"
- [ ] Check all texts

**Comment by jaywink** [comment]
Awesome stuff man! <3

I'll happily make the html into jade templates once you've done your magic. Will try to get some comments on actual content as soon as possible. The design already looks really good, I totally like the way it is going.

**Comment by Flaburgan** [comment]
Changed the list to a table. I will comment here when I make new changes.

**Comment by Flaburgan** [comment]
@jaywink I really want to continue to work on this, how can we proceed, can we maybe pick a date to work together on it? An evening during the week?

**Comment by jaywink** [comment]
@Flaburgan Yeah would be great to get this done! Do you have any more stuff you want to add before I transform your work into Jade templates and see how actual data sits in? Because after it is made into templates you can't submit more commits to these files you've done.

I can then push it to something like dev.the-federation.info for example and we can iterate on that then.

**Comment by Flaburgan** [comment]
Hm, I still have work to do for sure, but I would try to integrate with real data. What's the point of using Jade, I don't get it. Wouldn't be possible to use a template engine which keep traditional syntax of HTML?

**Comment by jaywink** [comment]
Just something I chose at the time. It's quite nice and clean. But I'm all open for options, if you have something other in mind that works nicely with Node.

**Comment by jaywink** [comment]
OK, [Nunjucks](https://mozilla.github.io/nunjucks/) seems like a good plan. Based on Jinja (the best template language in Python world, itself based on the Django template language). As a bonus, it's by Mozilla :)

Good plan?

**Comment by Flaburgan** [comment]
Looks good to me :+1: 

Let's create a new branch "new design" and integrate Nunjucks in. I'll then open PRs with my work on this branch.

**Comment by Flaburgan** [comment]
@jaywink any chance you can create the branch? Not sure how you would be able to reintegrate mine if I open one first...

**Comment by jaywink** [comment]
Well, it's not that simple. Need to convert the existing stuff first, just opening a branch doesn't really make sense :)

If you want, you can take the current master, add Nunjucks and start hacking on the templates. I'll try to put some time into this in the coming weeks though.

**Comment by jaywink** [comment]
@Flaburgan finally working on converting the existing templates to Nunjucks. Will hope to finish in a few days, you can then if you have time start tinkering with the design.

I would like the graphs still to be there, I think your design was missing them. And a pod list available. But they don't need to be on the landing page, they can be under another sub page for example.

Hopefully we can get this redesign live soon :)

**Comment by Flaburgan** [comment]
I have a global idea of what can be done, and the graphs will be part of idea don't worry, it's the basis of the website ;) You probably don't need to port the actual page to Nunjucks and show me a basic example of how the MVC is working and where to put the View files, and I'll write the front-end part ;)

**Comment by jaywink** [comment]
@Flaburgan here you go, all the templates are now Nunjucks via #48 . I wanted to convert the old stuff first so you don't have to rush.

![](https://usatftw.files.wordpress.com/2015/05/ryu.gif)

Basically it's a one page site with only the index view. The data comes in via JSON endpoints which you don't need to or shouldn't touch (or at least don't remove anything, you can add). If you want to add more pages, just define the routes in `routes.js` and load them in `app.js` - see the files.

 The current html is horrible, I cringe whenever I look at it. Please burn it with fire :) Bonus points for pulling in the vendor statics via Bower or something if you want.

Oh and can we keep the old logo somewhere, pretty pleeeeazeee? I've grown fond of it :D In the OG tag or footer if nowhere else..

Lemme know if you need help with something, IRC jaywink or FreeNode #thefederation is good for quick chat. Occasional WIP screenshots would be nice too :)

**Comment by Flaburgan** [comment]
So a lot of work has been accomplished. #42 has been merged in the `redesign` branch and 16 PRs have followed, we're seeing the light at the end of the tunnel!

Everyone can see the current state of this work at https://dev.the-federation.info thanks to @jaywink who deploys it after every merge so almost everyday.

I'm going to edit the first message of this issue to add what's still needed to do before merging `redesign` to `master`.

**Comment by goobertron** [comment]
Hey, this is great work. Thanks very much!

**Comment by Flaburgan** [comment]
Glad you like it! It's almost done so if you have any feedback please share it, I'm open to every suggestions.

**Comment by jaywink** [comment]
"Comments per user" button is overflowing on the graphs, is that the CSS glitch mentioned in the TODO's?

**Comment by Flaburgan** [comment]
Yep. Also including responsive everywhere ;)

**Comment by Flaburgan** [comment]
Alright everyone with https://github.com/jaywink/the-federation.info/pull/93 the dev work reached the state we targeted for a first release. Now is the time to fill the texts and review everything! 

Please go to https://dev.the-federation.info and check everything, every remark is welcome! 
@annando @redmatrix if you could provide text for Friendica and Hubzilla it would be awesome! We need a subtitle and a description for the project.

**Comment by jaywink** [comment]
@annando @redmatrix you can also just do a PR against the `redesign` branch (or master soon) directly - saves time 👍

**Comment by annando** [comment]
I see comments on https://dev.the-federation.info/node/squeet.me - but not on the overview. Is this a bug?

Concerning the texts: Do you think that you could pick up content from our beta page? http://beta.friendi.ca/about/

I'm not completely sure about the amount of words. So you could maybe take as much as you like from there?

**Comment by Flaburgan** [comment]
YAAAAY!
